Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,40 +11,38 @@ jobs:
     name: Test and build
     environment: snyk-npm
     runs-on: ubuntu-latest
-
-strategy:
-  matrix:
-    node-version: [16.x]
+    strategy:
+      matrix:
+        node-version: [16.x]
 
     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
-
-steps:
-  - uses: actions/checkout@v2
-  - name: Use Node.js ${{ matrix.node-version }}
-    uses: actions/setup-node@v2
-    with:
-      node-version: ${{ matrix.node-version }}
-      cache: 'npm'
-
-  - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
-    run: |
-      npm install snyk -g
-      npm install snyk-to-html -g
-      snyk auth ${{secrets.SNYK_AUTH}}
-
-  - name: Snyk Open Source # For testing and failing please add snyk test before snyk monitor
-    run: |
-      snyk monitor
-  # For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
-
-  - name: Snyk Code # Remove || true to fail if there are vulnerabilities
-    run: |
-      snyk code test || true
-  - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
-    run: |
-      docker build . -t MSsnyk-goof:latest
-      snyk container monitor MSsnyk-goof:latest --file=Dockerfile
-      
-  - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
-    run: |
-      snyk iac test || true
+    steps:
+      - uses: actions/checkout@v2
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
+    
+      - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
+        run: |
+          npm install snyk -g
+          npm install snyk-to-html -g
+          snyk auth ${{secrets.SNYK_AUTH}}
+    
+      - name: Snyk Open Source # For testing and failing please add snyk test before snyk monitor
+        run: |
+          snyk monitor
+      # For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
+    
+      - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+        run: |
+          snyk code test || true
+      - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+        run: |
+          docker build . -t MSsnyk-goof:latest
+          snyk container monitor MSsnyk-goof:latest --file=Dockerfile
+          
+      - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+        run: |
+          snyk iac test || true
